#!/bin/sh
#
#    10-help-text-zynq7010 - print the help text associated with the distro
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

printf "\n"
printf "     _______..__   __. .______         .___________. _______     _______.___________. _______ .______      \n"
printf "    /       ||  \ |  | |   _  \        |           ||   ____|   /       |           ||   ____||   _  \     \n"
printf "   |   (----\`|   \|  | |  |_)  |       \`---|  |----\`|  |__     |   (----\`---|  |----\`|  |__   |  |_)  |    \n"
printf "    \   \    |  . \`  | |      /            |  |     |   __|     \   \       |  |     |   __|  |      /     \n"
printf ".----)   |   |  |\   | |  |\  \----.       |  |     |  |____.----)   |      |  |     |  |____ |  |\  \----.\n"
printf "|_______/    |__| \__| | _| \`._____|       |__|     |_______|_______/       |__|     |_______|| _| \`._____|\n"

printf "\n"
printf " * RFS Built By: Nightseas <haixiaolee@gmail.com>\n"
printf " * Description:  Ubuntu rootfs for Intel Atom C5000 platform.\n"
